package com.hiennt.hienntbusiness.entity;
// Generated Nov 1, 2017 4:33:10 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TblCustomer generated by hbm2java
 */
@Entity
@Table(name = "tbl_customer", catalog = "f13_nth_businessdb")
public class TblCustomer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer cusId;
	private String cusName;
	private String cusAddress;
	private String cusCity;
	private String cusState;
	private String cusZip;
	private String cusPhone;
	private Set<TblInvoice> tblInvoices = new HashSet<TblInvoice>(0);

	public TblCustomer() {
	}

	public TblCustomer(String cusName, String cusAddress, String cusCity, String cusState, String cusZip,
			String cusPhone, Set<TblInvoice> tblInvoices) {
		this.cusName = cusName;
		this.cusAddress = cusAddress;
		this.cusCity = cusCity;
		this.cusState = cusState;
		this.cusZip = cusZip;
		this.cusPhone = cusPhone;
		this.tblInvoices = tblInvoices;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "cus_id", unique = true, nullable = false)
	public Integer getCusId() {
		return this.cusId;
	}

	public void setCusId(Integer cusId) {
		this.cusId = cusId;
	}

	@Column(name = "cus_name")
	public String getCusName() {
		return this.cusName;
	}

	public void setCusName(String cusName) {
		this.cusName = cusName;
	}

	@Column(name = "cus_address")
	public String getCusAddress() {
		return this.cusAddress;
	}

	public void setCusAddress(String cusAddress) {
		this.cusAddress = cusAddress;
	}

	@Column(name = "cus_city", length = 40)
	public String getCusCity() {
		return this.cusCity;
	}

	public void setCusCity(String cusCity) {
		this.cusCity = cusCity;
	}

	@Column(name = "cus_state", length = 2)
	public String getCusState() {
		return this.cusState;
	}

	public void setCusState(String cusState) {
		this.cusState = cusState;
	}

	@Column(name = "cus_zip", length = 10)
	public String getCusZip() {
		return this.cusZip;
	}

	public void setCusZip(String cusZip) {
		this.cusZip = cusZip;
	}

	@Column(name = "cus_phone", length = 11)
	public String getCusPhone() {
		return this.cusPhone;
	}

	public void setCusPhone(String cusPhone) {
		this.cusPhone = cusPhone;
	}

	@OneToMany(mappedBy = "tblCustomer", cascade = CascadeType.ALL)
	@JsonIgnore
	public Set<TblInvoice> getTblInvoices() {
		return this.tblInvoices;
	}

	public void setTblInvoices(Set<TblInvoice> tblInvoices) {
		this.tblInvoices = tblInvoices;
	}

}
