package com.hiennt.hienntbusiness.entity;
// Generated Nov 1, 2017 4:33:10 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblInvoiceId generated by hbm2java
 */
@Embeddable
public class TblInvoiceId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int cusId;
	private int proId;

	public TblInvoiceId() {
	}

	public TblInvoiceId(int cusId, int proId) {
		this.cusId = cusId;
		this.proId = proId;
	}

	@Column(name = "cus_id", nullable = false)
	public int getCusId() {
		return this.cusId;
	}

	public void setCusId(int cusId) {
		this.cusId = cusId;
	}

	@Column(name = "pro_id", nullable = false)
	public int getProId() {
		return this.proId;
	}

	public void setProId(int proId) {
		this.proId = proId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblInvoiceId))
			return false;
		TblInvoiceId castOther = (TblInvoiceId) other;

		return (this.getCusId() == castOther.getCusId()) && (this.getProId() == castOther.getProId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCusId();
		result = 37 * result + this.getProId();
		return result;
	}

}
