package com.hiennt.hienntbusiness.entity;
// Generated Nov 1, 2017 4:33:10 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblInvoice generated by hbm2java
 */
@Entity
@Table(name = "tbl_invoice", catalog = "f13_nth_businessdb")
public class TblInvoice implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TblInvoiceId id;
	private TblCustomer tblCustomer;
	private TblProduct tblProduct;
	private Integer numbers;
	private Date issueDate;
	private Float totalPayment;

	public TblInvoice() {
	}

	public TblInvoice(TblInvoiceId id, TblCustomer tblCustomer, TblProduct tblProduct) {
		this.id = id;
		this.tblCustomer = tblCustomer;
		this.tblProduct = tblProduct;
	}

	public TblInvoice(TblInvoiceId id, TblCustomer tblCustomer, TblProduct tblProduct, Integer numbers, Date issueDate,
			Float totalPayment) {
		this.id = id;
		this.tblCustomer = tblCustomer;
		this.tblProduct = tblProduct;
		this.numbers = numbers;
		this.issueDate = issueDate;
		this.totalPayment = totalPayment;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "cusId", column = @Column(name = "cus_id", nullable = false)),
			@AttributeOverride(name = "proId", column = @Column(name = "pro_id", nullable = false)) })
	public TblInvoiceId getId() {
		return this.id;
	}

	public void setId(TblInvoiceId id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "cus_id", nullable = false, insertable = false, updatable = false)
	public TblCustomer getTblCustomer() {
		return this.tblCustomer;
	}

	public void setTblCustomer(TblCustomer tblCustomer) {
		this.tblCustomer = tblCustomer;
	}

	@ManyToOne
	@JoinColumn(name = "pro_id", nullable = false, insertable = false, updatable = false)
	public TblProduct getTblProduct() {
		return this.tblProduct;
	}

	public void setTblProduct(TblProduct tblProduct) {
		this.tblProduct = tblProduct;
	}

	@Column(name = "numbers")
	public Integer getNumbers() {
		return this.numbers;
	}

	public void setNumbers(Integer numbers) {
		this.numbers = numbers;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "issue_date", length = 19)
	public Date getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	@Column(name = "total_payment", precision = 12, scale = 0)
	public Float getTotalPayment() {
		return this.totalPayment;
	}

	public void setTotalPayment(Float totalPayment) {
		this.totalPayment = totalPayment;
	}

}
